### ISSUE TITLE
IKControl setting has animations play on top, causing issues with body parts moving strangely

### ISSUE THREAD

**Issue by ghost** [TheNexusAvenger/Nexus-VR-Character-Model#31]
I currently have an issue where using the new IKControl setting makes animations still play on top of the VR character model systems. This is a major issue as the animations can cause very strange movements and have the arms/legs constantly moving incorrectly. This definitely can cause a lot of issues. Currently, the only workaround at the moment is disabling the provided IKControl setting.
https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/assets/116863714/9218fd69-7125-4b07-be2e-5d44f3e99ca5
_The video was recorded on Standalone Quest 2, but it also works on PCVR as well using the Quest 2._

**Comment by TheNexusAvenger** [comment]
Even without the IKControl + constraints beta, this behavior has not been observed in the 3 games I maintain. It is not obvious what is going on, or why it is only with IKControl.

**Comment by GinisDev** [comment]
I found that setting the animation priority to core reduces the effect of the animation. You could disable all animations for the character.

**Comment by TheNexusAvenger** [comment]
V.2.7.0 removed stopping all animations. I don't want to re-introduce that because of compatibility issues.
I don't see this being fixed in Nexus VR Character Model. V.3.0.0-preview1 is out now and gets rid of controller the character entirely. I highly doubt 2.11.0 will ever exist.

**Comment by TheNexusAvenger** [comment]
Any idea if this is an issue within maybe the last 3 months? I want to eventually change `IKControl` to be enabled by default, but I don't know if now is the time.

**Comment by ghost** [comment]
This is still an issue https://devforum.roblox.com/t/needs-maintainer-nexus-vr-character-model-open-source/109055/200

I always have IKControl disabled because of this

**Comment by TheNexusAvenger** [comment]
I have finally figured out the root cause. It is due to the [character overriding the torso's motors](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/init.luau#L485-L488). When the animations are calculated with the `IKControl`s, all of the math is correct, but is then made incorrect by the torso being changed *after* the calculations are done.

The bad news is I don't know of a quick fix. Renaming the `LowerTorso` is the simplest solution (and only solution?), but looks *horrible* with some animations (and more importantly, breaks compatibility with games that reference the `LowerTorso`). This is something I will need some help with to properly address.
